### ISSUE TITLE
Problem with configuration template

### ISSUE THREAD

**Issue by labg0re** [robertdebock/ansible-role-logrotate#1]
Running this role produces the following error on Debian 10:

`fatal: [node001]: FAILED! => {
 "msg": "The task includes an option with an undefined variable. The error was: 'logrotate_service' is undefined\n\nThe error appears to be in '/mnt/nfs/ansible/roles/robertdebock.logrotate/tasks/main.yml': line 29, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: start and enable logrotate\n  ^ here\n"
}`

**Comment by robertdebock** [comment]
hi @labg0re,

Thanks for your report, I'll try to reproduce it and write a fix.

**Comment by robertdebock** [comment]
Wow, that's a silly mistake, I'll make a fix for it, thanks once again!

**Comment by robertdebock** [comment]
This issue has been resolved with the latest pull request.

Thanks @labg0re for making the issue!
