### ISSUE TITLE
Add dateyesterday feature to role

### ISSUE THREAD

**Issue by DaisyDomergue** [robertdebock/ansible-role-logrotate#13]
## Proposed feature

add the dateyesterday feature of logrotate to enable rotated logs at midnight to have corresponding date

## Rationale

Why is this feature required?

I rotate logs at midnight and the rotated files have dates of the time they are created rather than the actual time of the contents

## Additional context

Add any other context about the feature request here.

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).

**Comment by walbertus** [comment]
I think it can be closed
