### ISSUE TITLE
`logrotate_keep` cannot be `-1` even it is a valid value

### ISSUE THREAD

**Issue by mbideau-atreal** [robertdebock/ansible-role-logrotate#18]
Hi and thank for this Ansible role.

I wanted to setup a _logrotate_ that always keep logs with the value `-1` but it is denied by the role : I got the following error message :

```
TASK [logrotate : assert | Test if logrotate_keep is set correctly] **************************************************************************************************************************
fatal: [192.168.1.21 -> localhost]: FAILED! => {"assertion": "logrotate_keep >= 0", "changed": false, "evaluated_to": false, "msg": "Assertion failed"}
```

The man of _logrotate_ says :
```
❯ man logrotate | grep '\-1'
              [...] If count is -1, old logs are not removed at all, except they are affected by maxage (use with caution, may waste performance and disk space).  Default is 0.
```

May be the test should be `logrotate_keep >= -1` ?

Thanks again.
Best regards.

**Comment by robertdebock** [comment]
Fixes, will release a new version soon.

**Comment by robertdebock** [comment]
Interesting, works on [some version of logrotate](https://github.com/robertdebock/ansible-role-logrotate/actions/runs/8843744542/job/24284434483).

I've kept the code to allow negative, but am not testing it.

**Comment by robertdebock** [comment]
Only [RHEL8](https://github.com/robertdebock/ansible-role-logrotate/actions/runs/8843856869/job/24284750047#step:4:5375) has this issue... Weird.
