### ISSUE TITLE
Add delaycompress option

### ISSUE THREAD

**Issue by antofthy** [robertdebock/ansible-role-logrotate#9]
## Proposed feature

Addition of delaycompress option

## Rationale

Delay compress is useful when you regularly read log files.
It is also a must when daemons may not switch over from old to new logs quickly

**Comment by antofthy** [comment]
code to add included in pull request
https://github.com/robertdebock/ansible-role-logrotate/pull/8

**Comment by robertdebock** [comment]
This has been done in the meantime.
